services:
# PHP application service
  app:
    build:
      context: ./xiang-app
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - app-network
# Nginx web server service using a custom configuration file
  nginx:
    build:
      context: ./xiang-app
      dockerfile: .docker/Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network
# MySQL database service
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xiang
      MYSQL_USER: xiang_admin
      MYSQL_PASSWORD: xiang123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
# Site to see the database without needing to use the command line
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: xiang_admin
      PMA_PASSWORD: xiang123
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge